source "http://rubygems.org"
gem "builder"
gem "bundler"
gem "nokogiri"
gem "marc"
gem "rdf"
gem "rdf-rdfxml"
gem "rdf-n3"
gem "rdf-virtuoso"
gem "rdf-spec"
gem "rspec-mocks"
gem "oai", '0.2.0'
gem "rest-client"
gem "rack"
gem "grape"
gem "sinatra"
gem "sinatra-contrib"
gem "sequel"
gem "sqlite3"
gem "slim"
gem "thin"
gem "foreman"

group :development do
  gem "sinatra-reloader"
  gem "pry"
end
