source "http://rubygems.org"
gem "builder"
gem "nokogiri"
gem "marc"
gem "yaml"
gem "rdf"
gem "rdf-rdfxml"
gem "rdf-n3"
gem "rest-client"
gem "oai", '0.0.9', :git => 'git://github.com/teefax/oai.git'
